version: '3.5'

networks:
  inception_network:
    name: inception_network
    driver: bridge

services:
  mariadb:
      image: mariadb
      container_name: mariadb
      ports:
      - 3306:3306
      networks: 
        - inception_network
      volumes:
      - /home/oronda/data/mysql:/var/lib/mysql
      env_file:
        - .env
      restart: unless-stopped

  wordpress:
    image:  wordpress:php7.3-fpm-alpine
    container_name: wordpress
    depends_on:  
      - mariadb
    env_file:
        - .env
    volumes: 
      - /home/oronda/data/html:/var/www/html  
    #links:
    #  - mariadb    
    networks: 
      - inception_network
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:  
      - wordpress
    ports:
      - 443:443   
    volumes:  
      - /home/oronda/Desktop/Inception/srcs/requirements/nginx/conf/:/etc/nginx/conf.d 
      - /home/oronda/data/html:/var/www/html 
    networks: 
      - inception_network
    #links:
    #  - wordpress

  