version: '3' 

services:


  mariadb:
    build: requirements/mariadb
    image: mariadb
      #restart: always
    container_name: mariadb_inception
    volumes:
      - /home/oronda/data:/var/lib/mysql
    networks:
      - inception_network
    ports:
      - 3306:3306
    env_file:
      - .env

networks:
  inception_network:
    driver: bridge
