version: '3'
services:
  mariadb:
      image: mariadb
      container_name: mariadb
      volumes:
      - /home/oronda/data/mysql:/var/lib/mysql
      ports:
      - 3306:3306
      networks: 
        - inception_network
      env_file:
        - .env 
      restart: always
      


  wordpress:
    image:  wordpress:php7.3-fpm-alpine
    container_name: wordpress
    volumes: 
      - /home/oronda/data/html:/var/www/html   
    depends_on:  
      - mariadb   
    ports:
      - 9000:9000  
    networks: 
      - inception_network
    env_file:
      - .env
    restart: always


  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:  
      - /home/oronda/Desktop/Inception/srcs/requirements/nginx/conf:/etc/nginx/conf.d 
      - /home/oronda/data/html:/var/www/html 
    ports:
      - 443:80 
    env_file:
      - .env  
    networks: 
      - inception_network

networks:
  inception_network: