version: '3.7'
services:
  mariadb:
      build: requirements/mariadb
      container_name: mariadb
      ports:
      - 3306:3306
      networks: 
        - inception_network
      volumes:
      - mariadb-volume:/var/lib/mysql
      env_file:
        - .env
      restart: unless-stopped

  
volumes:
  mariadb-volume:
    driver_opts:
      o: bind
      device: "/home/oronda/data/mysql"
      type: none
    driver: local
  
networks:
  inception_network:
    name: inception_network
    driver: bridge

  