version: '3.7'
services:
  mariadb:
      build: requirements/mariadb
      container_name: mariadb
      ports:
      - 3306:3306
      networks: 
        - inception_network
      volumes:
      - /home/oronda/data/mysql:/var/lib/mysql
      env_file:
        - .env
      restart: unless-stopped

  nginx:
      build: requirements/nginx
      container_name: nginx
      depends_on:  
        - wordpress
      ports:
        - 443:443
      volumes: 
       - /home/oronda/data/html/wordpress:/var/www/html/wordpress
      networks: 
        - inception_network
      restart: unless-stopped

  wordpress:
      build: requirements/wordpress
      container_name: wordpress
      depends_on:  
        - mariadb
      env_file:
          - .env
      ports:
        - 9000:9000 
      volumes: 
       - /home/oronda/data/html/wordpress:/var/www/html/wordpress
      networks: 
        - inception_network
      restart: always
  

  adminer:
    image: adminer
    depends_on:  
        - mariadb
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks: 
        - inception_network
    

networks:
  inception_network:
  